[project]
dynamic = ["version"]
name = "calories-py"
description = "This package is a dependency-free package that estimates calories burned during physical activities (walking, hiking, rucking, etc) with functions for both simple calorie estimates, and more advanced methods utilizing GPS data."
readme = "Readme.md"
requires-python = ">=3.9"
license = "ISC"
license-files = ["LICENSE"]
authors = [
  { name="Matthew Duffy", email="mattduffy@gmail.com" }
]
maintainers = [
  { name="Matthew Duffy", email="mattduffy@gmail.com" }
]
keywords = [
    "calories burned",
    "walk", "walking", "hike", "hiking", "ruck", "rucking",
    "metabolic rate", "joules per kcal", "terrain coefficients",
    "MET", "Metabolic Equivalent Tasks", "3.5 ml O2/(kg per min)", "Joules per Kcalorie",
    "Basal Metabolic Rate", "VO2 Max", "VO2 Rest", "Mifflin-St Jeor",
    "pandolf", "santee", "pandolf-santee", "calorie predictive model",
    "LCDA", "load carrying decision application",
    "Minimum Mechanics"
]
dependencies = []
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/mattduffy/calories-py"
Issues = "https://github.com/mattduffy/calories-py/issues"

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.targets.wheel]
# Maps the local file to the root of the installed package
packages = ["src/calories"]

[tool.hatch.build.targets.sdist]
include = [
  "src/calories/**/*.py",
  "src/calories/**/*.json",
]